import cx_Freeze
import os
os.environ['TCL_LIBRARY'] = "/System/Library/tcl/8.4"


executables = [cx_Freeze.Executable("game.py")]
files = ["Big Chillum_David Starfire.wav",
         "Jumping Off_David Starfire.wav",
         "Knight Riddum_David Starfire.wav",
         "Rahu_David Starfire.wav",
         "Shiva Lives_David Starfire.wav",
         "The One_(feat Alex Grey and Joaqopelli)_(Original Mix)_David Starfire.wav",
         "joog_shooters_instructions.png",
         "joog_shooters_instructions2.png",
         "joog_shooters_title.png",
         "Pixel-Art-BackGround1.png",
         "Pixelated_BG1.png",
         "Pixelated_BG2.png",
         "Pixelated_BG3.png",
         "Smooth_pixel_BG.png",
         "synth-wave-retro-city-landscape.png",
         "checked_box-01.png",
         "info_icon.png",
         "music_play.png",
         "music_play_hover.png",
         "music_previous.png",
         "music_previous_hover.png",
         "music_skip.png",
         "music_skip_hover.png",
         "PlaylistBtn.png",
         "QuitGameBtn.png",
         "QuitGameBtn_hover.png",
         "RestartBtn.png",
         "RestartBtn_hover.png",
         "RsmBtn.png",
         "RsmBtn_hover.png",
         "unchecked_box-01.png",
         "X_Btn-01.png",
         "?box.png",
         "GunIcon1.png",
         "GunIcon2.png",
         "Joog_turret.png",
         "p1_weapon_slash.png",
         "p2_weapon_slash.png",
         "pause_menu_border.png",
         "platform_tiles_sheet_blue.png",
         "Player1_Large.png",
         "Player2_Large.png",
         "Sprite1_sheet.png",
         "Sprite2_sheet.png",
         "SwordIcon1.png",
         "SwordIcon2.png",
         "weapons_sheet.png",
         "P1FORWARD.png",
         "P2FORWARD.png",
         "icon.ico",
         "icon.icns",
         ]
excludes = ["numpy.core._dotblas",
            "numpy.linalg._umath_linalg",
            "numpy.linalg.lapack_lite",
            "scipy.lib.lapack",
            "scipy.lib.blas.fblas", "tcl"]

cx_Freeze.setup(
    name="JS",
    options={"build_exe": {"packages": ["pygame", "tkinter"], "include_files": files, "excludes": excludes}},
    executables=executables
)
